name: Generate Snake

on:
  schedule:
    - cron: "0 */24 * * *" # tous les 24h
  workflow_dispatch:


permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:


      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ErwannHillion
          outputs: dist/github-contribution-grid-snake.svg
          palette: github-dark


      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: "Deploy snake"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
