name: Generate Snake

on:
  schedule:
    - cron: "0 */24 * * *" # tous les 24h
  workflow_dispatch:

# ⬅️ Donne l'accès en écriture au token
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # (facultatif) checkout si tu veux, pas obligatoire ici
      # - uses: actions/checkout@v4

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ErwannHillion
          outputs: dist/github-contribution-grid-snake.svg

      # ⚠️ Passe à la v3 de l'action gh-pages
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: "Deploy snake"
          # si tu veux l’historique propre:
          # keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
